name: Run PyTest

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker image
        run: |
          cd ci-cd
          docker buildx create --use
          docker buildx build -t spotify-tests:latest . --load

      - name: Run tests in Docker container
        run: |
          docker run --name test-container spotify-tests
          exit_code=$?
          docker cp test-container:/pytest_report.html ./pytest_report.html
          docker stop test-container
          if [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: PyTest Report
          path: ./pytest_report.html
